
let state={screen:"home",quizIndex:0,selected:null,score:0,quizDone:false,showFeedback:false,simIndex:0,simScore:0};
const defaultProgress={Observer:50,Analyser:50,Prioriser:50,Décider:50,Communiquer:50,Transmettre:50,Réfléchir:50,"Se professionnaliser":50};
function getProgress(){return JSON.parse(localStorage.getItem("praxis_progress")||JSON.stringify(defaultProgress))}
function saveProgress(p){localStorage.setItem("praxis_progress",JSON.stringify(p))}
function getStats(){return JSON.parse(localStorage.getItem("praxis_stats")||JSON.stringify({quizzes:0,sims:0,lastScore:0}))}
function saveStats(s){localStorage.setItem("praxis_stats",JSON.stringify(s))}
function avg(){let v=Object.values(getProgress());return Math.round(v.reduce((a,b)=>a+b,0)/v.length)}
function updateProgress(cap,ok){let p=getProgress();p[cap]=Math.max(0,Math.min(100,(p[cap]||50)+(ok?4:-1)));saveProgress(p)}
function setScreen(s){state.screen=s;render()}
function render(){document.getElementById("app").innerHTML=`<div class="phone"><div class="header"><h1>Praxis Academy</h1><p>Comprendre • S'exercer • Réussir</p></div><div class="content">${renderScreen()}</div><div class="nav"><button onclick="setScreen('home')">Accueil</button><button onclick="setScreen('quiz')">Quiz</button><button onclick="setScreen('passport')">Passeport</button><button onclick="setScreen('sim')">Sim</button><button onclick="setScreen('admin')">Admin</button></div></div>`}
function renderScreen(){return state.screen==="quiz"?renderQuiz():state.screen==="passport"?renderPassport():state.screen==="sim"?renderSim():state.screen==="admin"?renderAdmin():renderHome()}
function renderHome(){let s=getStats(),a=avg();return `<div class="card"><span class="badge">Pilote IFSI</span><h2>Bonjour Léa 👋</h2><p class="small">Année 2 • Semestre 1 • Module vitrine</p></div><div class="card"><h3>Progression globale</h3><div class="progress"><span style="width:${a}%"></span></div><strong>${a} %</strong></div><div class="card"><h3>Objectif recommandé</h3><p>Raisonnement clinique : prioriser une situation.</p><button class="btn" onclick="startQuiz()">Commencer le quiz</button></div><div class="card"><h3>Derniers résultats</h3><div class="stat"><span>Quiz réalisés</span><strong>${s.quizzes}</strong></div><div class="stat"><span>Praxis Sim réalisées</span><strong>${s.sims}</strong></div><div class="stat"><span>Dernier score</span><strong>${s.lastScore} %</strong></div></div>`}
function startQuiz(){state.quizIndex=0;state.selected=null;state.score=0;state.quizDone=false;state.showFeedback=false;setScreen("quiz")}
function selectAnswer(i){state.selected=i;render()}
function validateAnswer(){if(state.selected===null){alert("Choisissez une réponse.");return}let q=PRAXIS_QUESTIONS[state.quizIndex],ok=state.selected===q.correct;if(ok)state.score++;updateProgress(q.capability,ok);state.showFeedback=true;render()}
function nextQuestion(){state.selected=null;state.showFeedback=false;state.quizIndex++;if(state.quizIndex>=PRAXIS_QUESTIONS.length){state.quizDone=true;let pct=Math.round(state.score/PRAXIS_QUESTIONS.length*100),s=getStats();s.quizzes++;s.lastScore=pct;saveStats(s)}render()}
function renderQuiz(){if(state.quizDone){let pct=Math.round(state.score/PRAXIS_QUESTIONS.length*100);return `<div class="card"><h2>Résultat du quiz</h2><h1>${pct} %</h1><p>${state.score} bonnes réponses sur ${PRAXIS_QUESTIONS.length}</p><p>${pct>=70?"Votre raisonnement est cohérent.":"Certaines capacités méritent encore un entraînement."}</p><button class="btn" onclick="setScreen('passport')">Voir mon Passeport</button><button class="btn light" onclick="startQuiz()">Refaire le quiz</button></div>`}let q=PRAXIS_QUESTIONS[state.quizIndex],good=state.selected===q.correct;return `<div class="card"><p class="small">Question ${state.quizIndex+1}/${PRAXIS_QUESTIONS.length} • ${q.capability} • ${q.competence}</p><h2>${q.question}</h2>${q.answers.map((a,i)=>`<button class="answer ${state.selected===i?"selected":""}" onclick="selectAnswer(${i})">${String.fromCharCode(65+i)}. ${a}</button>`).join("")}${!state.showFeedback?`<button class="btn" onclick="validateAnswer()">Valider</button>`:""}</div>${state.showFeedback?`<div class="feedback ${good?"":"error"}"><h3>${good?"Bonne réponse":"Réponse à retravailler"}</h3><p><strong>Bonne réponse :</strong> ${q.answers[q.correct]}</p><p><strong>Observation Praxis :</strong> ${q.explanation}</p><button class="btn secondary" onclick="nextQuestion()">Continuer</button></div>`:""}`}
function renderPassport(){let p=getProgress(),a=avg();return `<div class="card"><h2>Passeport Praxis</h2><h1>${a} %</h1><p>Progression globale</p></div><div class="card"><h3>Capacités Praxis</h3>${Object.entries(p).map(([k,v])=>`<div class="skill"><span>${k}</span><div class="progress"><span style="width:${v}%"></span></div><strong>${v}%</strong></div>`).join("")}</div><div class="card"><h3>Recommandation Praxis</h3><p>Priorité actuelle : renforcer la capacité <strong>Prioriser</strong> avec les Praxis Sim.</p><button class="btn" onclick="setScreen('sim')">Faire une Praxis Sim</button></div>`}
function renderSim(){let st=PRAXIS_SIM.steps[state.simIndex];if(!st){let pct=Math.round(state.simScore/PRAXIS_SIM.steps.length*100);return `<div class="card"><h2>Praxis Sim terminée</h2><h1>${pct} %</h1><p>${pct>=70?"Bonne démarche clinique.":"Raisonnement à consolider."}</p><button class="btn" onclick="resetSim()">Recommencer</button></div>`}return `<div class="card"><span class="badge">${PRAXIS_SIM.id}</span><h2>${PRAXIS_SIM.title}</h2><p><strong>${PRAXIS_SIM.patient}</strong></p><p>${PRAXIS_SIM.intro}</p></div><div class="card"><p class="small">Étape ${state.simIndex+1}/${PRAXIS_SIM.steps.length}</p><h3>${st.question}</h3>${st.answers.map((a,i)=>`<button class="answer" onclick="answerSim(${i})">${String.fromCharCode(65+i)}. ${a}</button>`).join("")}</div>`}
function answerSim(i){let st=PRAXIS_SIM.steps[state.simIndex],ok=i===st.correct;if(ok)state.simScore++;updateProgress("Prioriser",ok);alert((ok?"Bonne réponse. ":"Réponse à retravailler. ")+st.explanation);state.simIndex++;if(state.simIndex>=PRAXIS_SIM.steps.length){let s=getStats();s.sims++;saveStats(s)}render()}
function resetSim(){state.simIndex=0;state.simScore=0;setScreen("sim")}
function renderAdmin(){let s=getStats(),p=getProgress();let weak=Object.entries(p).filter(([k,v])=>v<60);return `<div class="card"><h2>Tableau formateur</h2><p class="small">Vue pilote simplifiée</p></div><div class="card"><h3>Activité</h3><div class="stat"><span>Quiz réalisés</span><strong>${s.quizzes}</strong></div><div class="stat"><span>Praxis Sim réalisées</span><strong>${s.sims}</strong></div><div class="stat"><span>Dernier score</span><strong>${s.lastScore} %</strong></div></div><div class="card"><h3>Compétences fragiles</h3>${weak.map(([k,v])=>`<div class="stat"><span>${k}</span><strong class="warning">${v}%</strong></div>`).join("")||"<p class='success'>Aucune fragilité majeure détectée.</p>"}</div>`}
render();
