
const PRAXIS_QUESTIONS=[
{id:"RC001",competence:"C1",capability:"Observer",question:"Un patient présente une respiration rapide, des sueurs et une agitation. Quel élément doit attirer votre attention en priorité ?",answers:["L'agitation","Les sueurs","La respiration rapide","L'heure","La position du lit"],correct:2,explanation:"La respiration rapide peut être un signe précoce de détresse respiratoire."},
{id:"RC002",competence:"C1",capability:"Observer",question:"Quel paramètre évalue directement l'oxygénation du patient ?",answers:["Température","Tension artérielle","Glycémie","SpO₂","Poids"],correct:3,explanation:"La SpO₂ mesure la saturation en oxygène et permet d'objectiver l'oxygénation."},
{id:"RC003",competence:"C2",capability:"Prioriser",question:"Un patient présente douleur 7/10, saturation 83 % et anxiété. Quelle priorité retenez-vous ?",answers:["Soulager l'anxiété","Soulager la douleur","Corriger l'altération respiratoire","Donner à boire","Installer la télévision"],correct:2,explanation:"Les fonctions vitales sont prioritaires. Une saturation à 83 % nécessite une attention immédiate."},
{id:"RC004",competence:"C1",capability:"Analyser",question:"Patient diabétique, plaie du pied et fièvre. Quelle hypothèse est la plus pertinente ?",answers:["Infection de la plaie","Entorse","Dépression","Asthme","Migraine"],correct:0,explanation:"Le diabète favorise les infections et retarde la cicatrisation."},
{id:"RC005",competence:"C11",capability:"Transmettre",question:"Lors d'une transmission, quelle information est la plus importante ?",answers:["Les opinions personnelles","Les faits observés","Les rumeurs","Les suppositions","Les habitudes du service"],correct:1,explanation:"Une transmission doit être factuelle, précise et utile à la continuité des soins."},
{id:"RC006",competence:"C2",capability:"Prioriser",question:"Quel patient doit être vu en premier ?",answers:["Douleur 2/10","Température 37,8°C","SpO₂ 82 %","Difficulté à dormir","Constipation"],correct:2,explanation:"Une SpO₂ à 82 % évoque une hypoxémie sévère nécessitant une réaction rapide."},
{id:"RC007",competence:"C1",capability:"Analyser",question:"Patient insuffisant cardiaque, prise de poids rapide et œdèmes. Quelle explication est probable ?",answers:["Déshydratation","Rétention hydrique","Allergie","Traumatisme","Migraine"],correct:1,explanation:"L'insuffisance cardiaque peut entraîner une rétention hydrosodée."},
{id:"RC008",competence:"C4",capability:"Décider",question:"Patient sous anticoagulant après une chute. Quel risque surveiller en priorité ?",answers:["Constipation","Hémorragie","Insomnie","Asthme","Myopie"],correct:1,explanation:"Les anticoagulants augmentent le risque de saignement après un traumatisme."},
{id:"RC009",competence:"C1",capability:"Observer",question:"Quel changement doit alerter immédiatement ?",answers:["Patient plus calme","Confusion brutale","Lecture du journal","Appétit conservé","Bonne hydratation"],correct:1,explanation:"Une confusion brutale peut révéler une urgence ou une complication médicale."},
{id:"RC010",competence:"C2",capability:"Décider",question:"Le raisonnement clinique consiste principalement à :",answers:["Appliquer mécaniquement","Mémoriser seulement","Observer, analyser, prioriser et agir","Répondre à des QCM","Suivre uniquement son intuition"],correct:2,explanation:"Le raisonnement clinique mobilise observation, analyse, priorisation et action adaptée."}
];
const PRAXIS_SIM={id:"SIM-RC01",title:"Dyspnée aiguë",patient:"Monsieur Martin, 72 ans",intro:"Dyspnée, SpO₂ 88 %, FR 28/min et FC 112/min.",steps:[
{question:"Que remarquez-vous en priorité ?",answers:["L'âge du patient","L'altération respiratoire","Le dossier administratif"],correct:1,explanation:"La SpO₂ basse et la fréquence respiratoire élevée orientent vers une altération respiratoire."},
{question:"Le patient devient agité. Quelle hypothèse est la plus pertinente ?",answers:["Agacement simple","Possible aggravation de l'hypoxie","Besoin de sommeil"],correct:1,explanation:"L'agitation peut être un signe d'aggravation de l'hypoxie."},
{question:"Quelle action doit être priorisée ?",answers:["Surveiller et alerter selon le protocole","Reporter au lendemain","Changer la télévision"],correct:0,explanation:"La sécurité du patient impose surveillance rapprochée et alerte selon l'organisation du service."}
]};
